# Generated by Django 5.0.3 on 2024-08-07 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand_object',
            field=models.CharField(max_length=200),
        ),
    ]
