# Generated by Django 5.0.3 on 2024-08-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_alter_product_brand_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_object',
            field=models.CharField(max_length=200),
        ),
    ]
